services:
  db:
    image: ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mark
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: calorie_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
volumes:
  pgdata:
